updates

diff --git a/bin/avconvert b/bin/avconvert
--- a/bin/avconvert
+++ b/bin/avconvert
@@ -15,11 +15,42 @@
 # Print a usage message and exit.
 display_usage() {
 	echo "This script must be run with arguments."
-	echo -e "\nUsage:\navconvert [directory] \n"
+	echo -e "\nUsage:\navconvert [directory] [extension] \n"
+	echo -e "Arguments:\nDirectory == The directory you want to iterate over.\n"
+	echo -e "\nExtension == The file format you want to operate on.\n"
+	echo -e "Example:\n ./avconvert /mnt/tvshows/ *.mkv"
+}
+
+# function for conversion of media file to mp4 format
+do_convert() {
+	for i in $(find $1 -type f -name $2 -print0 | xargs -0 -n 1);
+	do
+		avconv -y i "$i" -vcodec libx264 -acodec aac -strict experimental -threads 3 "${i%.*}.mp4";
+		rm "$i"
+		chmod 664 "${i%.*}.mp4";
+	done
+}
+
+# Log handling
+write_log()
+{
+  while read text
+  do
+      LOGTIME=`date "+%Y-%m-%d %H:%M:%S"`
+      # If log file is not defined, just echo the output
+      if [ "$LOG_FILE" == "" ]; then
+    echo $LOGTIME": $text";
+      else
+        LOG=$LOG_FILE.`date +%Y%m%d`
+    touch $LOG
+        if [ ! -f $LOG ]; then echo "ERROR!! Cannot create log file $LOG. Exiting."; exit 1; fi
+    echo $LOGTIME": $text" | tee -a $LOG;
+      fi
+  done
 }
 
 # if less than two arguments supplied, display usage
-if [  $# -le 0 ]
+if [  $# -le 1 ]
 then
 	display_usage
 	exit 1
@@ -32,30 +63,6 @@ then
 	exit 0
 fi
 
-for i in $(find $1 -type f -name '*.avi' -print0 | xargs -0 -n 1);
-do
-    avconv -y -i "$i" -vcodec libx264 -acodec aac -strict experimental -threads 3 "${i%.*}.mp4";
-	rm "$i";
-	chmod 664 "${i%.*}.mp4";
-done
+do_convert
 
-for i in $(find $1 -type f -name '*.mkv' -print0 | xargs -0 -n 1);
-do
-    avconv -y -i "$i" -vcodec libx264 -acodec aac -strict experimental -threads 3 "${i%.*}.mp4";
-	rm "$i";
-	chmod 664 "${i%.*}.mp4";
-done
-
-for i in $(find $1 -type f -name '*.m4v' -print0 | xargs -0 -n 1);
-do
-    avconv -y -i "$i" -vcodec libx264 -acodec aac -strict experimental -threads 3 "${i%.*}.mp4";
-	rm "$i";
-	chmod 664 "${i%.*}.mp4";
-done
-
-for i in $(find $1 -type f -name '*.mpg' -print0 | xargs -0 -n 1);
-do
-    avconv -y -i "$i" -vcodec libx264 -acodec aac -strict experimental -threads 3 "${i%.*}.mp4";
-	rm "$i";
-	chmod 664 "${i%.*}.mp4";
-done
+write_log
